name: .NET release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    strategy:
      matrix:
        os: [Windows-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write

    env:
      DOTNET_CONFIGURATION: Release

    steps:
    - uses: actions/checkout@v5
    - name: Setup Runtimes, Caching
      uses: ./.github/actions/setup-runtimes-caching
      with:
        name: "Full"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ env.DOTNET_CONFIGURATION }}

    - name: Test
      run: dotnet test --configuration ${{ env.DOTNET_CONFIGURATION }} --no-build --verbosity normal

    - name: Pack
      run: dotnet pack --configuration Release --no-restore --no-build --output artifacts -p:Version=${{ steps.get_version.outputs.VERSION }}

    - name: Publish NuGet packages as artifacts (for release)
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        if-no-files-found: error
        path: artifacts/*.nupkg

  release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./*.nupkg

  publish-nuget:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages

      - name: Publish on NuGet
        run: dotnet nuget push ./*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate